// Acervo inicial exibido enquanto o catálogo do Supabase estiver vazio ou indisponível.
// Os mesmos itens são inseridos pelo supabase/schema.sql (com UUIDs gerados pelo banco).
import type { Product } from './types';

const base = {
  gallery: [] as string[],
  season_compatibility: [] as string[],
  is_active: true,
  price_cents: null,
};

export const SEED_PRODUCTS: Product[] = [
  {
    ...base,
    id: 'seed-blazer-marinho',
    slug: 'blazer-tailored-super-120s-marinho',
    name: 'Blazer Tailored Super 120s',
    category: 'Alfaiataria',
    slot: 'sobreposicao',
    description: 'Corte italiano slim com ombros estruturados e forro acetinado. A peça que resolve da reunião ao jantar.',
    fabric: 'Lã fria Super 120s',
    color_name: 'Azul Marinho',
    hex_color: '#1B2A4A',
    image_url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=900&q=80',
    sizes: ['46', '48', '50', '52', '54'],
    skin_tones: ['clara', 'morena', 'parda', 'negra'],
    occasions: ['trabalho', 'jantar', 'festa', 'esporte'],
    climates: ['frio', 'ameno'],
    formality: 4,
    is_featured: true,
    sort_order: 10,
  },
  {
    ...base,
    id: 'seed-trico-terracota',
    slug: 'trico-cashmere-italiano-terracota',
    name: 'Tricô Cashmere Italiano',
    category: 'Malharia',
    slot: 'superior',
    description: 'Fios nobres de cashmere, gola careca reforçada e caimento fluido que não marca.',
    fabric: 'Cashmere',
    color_name: 'Terracota',
    hex_color: '#A0522D',
    image_url: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=900&q=80',
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: ['morena', 'parda', 'negra'],
    occasions: ['casual', 'barzinho', 'jantar'],
    climates: ['frio', 'ameno'],
    formality: 2,
    is_featured: true,
    sort_order: 20,
  },
  {
    ...base,
    id: 'seed-camisa-marfim',
    slug: 'camisa-pima-cotton-giza-marfim',
    name: 'Camisa Pima Cotton Giza',
    category: 'Camisaria',
    slot: 'superior',
    description: 'Algodão egípcio de fibra extralonga, brilho discreto e colarinho que se mantém firme o dia todo.',
    fabric: 'Algodão egípcio Giza',
    color_name: 'Branco Marfim',
    hex_color: '#F4EFE4',
    image_url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=900&q=80',
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['trabalho', 'jantar', 'festa', 'esporte', 'casual'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 30,
  },
  {
    ...base,
    id: 'seed-chino-grafite',
    slug: 'chino-tailored-cinza-grafite',
    name: 'Chino Tailored',
    category: 'Calças',
    slot: 'inferior',
    description: 'Bolsos faca, cós ajustado sem necessidade de cinto e elastano na medida certa para o movimento.',
    fabric: 'Algodão com elastano',
    color_name: 'Cinza Grafite',
    hex_color: '#2C3539',
    image_url: 'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?w=900&q=80',
    sizes: ['38', '40', '42', '44', '46'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'esporte'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 40,
  },
  {
    ...base,
    id: 'seed-costume-obsidian',
    slug: 'costume-noturno-obsidian',
    name: 'Costume Noturno',
    category: 'Alfaiataria',
    slot: 'sobreposicao',
    description: 'Paletó e calça em lã fria com toque acetinado. Silhueta limpa para casamentos e noites de gala.',
    fabric: 'Lã fria acetinada',
    color_name: 'Preto Obsidian',
    hex_color: '#0B0C10',
    image_url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=900&q=80',
    sizes: ['46', '48', '50', '52', '54'],
    skin_tones: ['parda', 'negra', 'clara'],
    occasions: ['festa', 'jantar', 'trabalho'],
    climates: ['frio', 'ameno'],
    formality: 5,
    is_featured: true,
    sort_order: 50,
  },
];
