// Acervo inicial: as peças reais da Titi's Store (fotos em /public/produtos).
// Exibido quando o catálogo do Supabase está vazio ou indisponível; as mesmas peças
// estão em supabase/produtos.sql. Gerado a partir de uma lista única — edite lá e regenere.
import type { Product } from './types';

function getProductPriceCents(slug?: string | null): number {
  const s = slug || '';
  if (s.includes('alfaiataria-regulador')) return 28990;
  if (s.includes('alfaiataria-cordao')) return 26990;
  if (s.includes('chino')) return 24990;
  if (s.includes('derby')) return 42990;
  if (s.includes('loafer')) return 38990;
  if (s.includes('tenis-couro-minimalista')) return 32990;
  if (s.includes('tenis')) return 34990;
  if (s.includes('polo')) return 19990;
  if (s.includes('camiseta-gola-alta')) return 14990;
  return 24990;
}

const base = {
  season_compatibility: [] as string[],
  is_active: true,
  price_cents: 24990,
};

const RAW_SEED_PRODUCTS: Product[] = [
  {
    ...base,
    id: 'seed-calca-alfaiataria-regulador-cinza-grafite',
    slug: 'calca-alfaiataria-regulador-cinza-grafite',
    name: 'Calça de Alfaiataria com Regulador',
    category: 'Calças',
    slot: 'inferior',
    description: 'Regulador lateral em metal e cós limpo: veste sem cinto e afina a silhueta. Caimento slim com barra no ponto para tênis ou loafer.',
    fabric: 'Sarja com elastano',
    color_name: 'Cinza Grafite',
    hex_color: '#4A4D52',
    image_url: '/produtos/calca-alfaiataria-regulador-cinza-grafite.jpg',
    gallery: ['/produtos/calca-alfaiataria-regulador-cinza-grafite-2.jpg'],
    sizes: ['38', '40', '42', '44', '46', '48'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'esporte'],
    climates: [],
    formality: 3,
    is_featured: true,
    sort_order: 10,
  },
  {
    ...base,
    id: 'seed-calca-chino-slim-azul-marinho',
    slug: 'calca-chino-slim-azul-marinho',
    name: 'Calça Chino Slim',
    category: 'Calças',
    slot: 'inferior',
    description: 'Chino de sarja com elastano, bolsos faca e barra reta. A base mais versátil do guarda-roupa: do escritório ao jantar.',
    fabric: 'Sarja de algodão com elastano',
    color_name: 'Azul Marinho',
    hex_color: '#1F2D45',
    image_url: '/produtos/calca-chino-slim-azul-marinho.jpg',
    gallery: [],
    sizes: ['38', '40', '42', '44', '46', '48'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'esporte'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 20,
  },
  {
    ...base,
    id: 'seed-calca-chino-slim-off-white',
    slug: 'calca-chino-slim-off-white',
    name: 'Calça Chino Slim',
    category: 'Calças',
    slot: 'inferior',
    description: 'Chino claro de sarja com elastano, bolsos faca e barra reta. Ilumina o look e combina com camurça, caramelo e tons de terra.',
    fabric: 'Sarja de algodão com elastano',
    color_name: 'Off-White',
    hex_color: '#E9E1D2',
    image_url: '/produtos/calca-chino-slim-off-white.jpg',
    gallery: [],
    sizes: ['38', '40', '42', '44', '46', '48'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 30,
  },
  {
    ...base,
    id: 'seed-calca-alfaiataria-regulador-preto',
    slug: 'calca-alfaiataria-regulador-preto',
    name: 'Calça de Alfaiataria com Regulador',
    category: 'Calças',
    slot: 'inferior',
    description: 'Preto absoluto com regulador lateral em metal e cós limpo. Caimento slim, sem cinto, para noites e ocasiões que pedem sobriedade.',
    fabric: 'Sarja com elastano',
    color_name: 'Preto',
    hex_color: '#101114',
    image_url: '/produtos/calca-alfaiataria-regulador-preto.jpg',
    gallery: ['/produtos/calca-alfaiataria-regulador-preto-2.jpg'],
    sizes: ['38', '40', '42', '44', '46', '48'],
    skin_tones: [],
    occasions: ['trabalho', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 4,
    is_featured: false,
    sort_order: 40,
  },
  {
    ...base,
    id: 'seed-calca-alfaiataria-cordao-azul-marinho',
    slug: 'calca-alfaiataria-cordao-azul-marinho',
    name: 'Calça de Alfaiataria com Cordão',
    category: 'Calças',
    slot: 'inferior',
    description: 'Vinco frontal marcado e cós com cordão: aparência de alfaiataria com conforto de malha. Disponível também em preto, marrom e azul petróleo.',
    fabric: 'Malha de alfaiataria',
    color_name: 'Azul Marinho',
    hex_color: '#1B2A4A',
    image_url: '/produtos/calca-alfaiataria-cordao-azul-marinho.jpg',
    gallery: ['/produtos/calca-alfaiataria-cordao-azul-marinho-2.jpg'],
    sizes: ['38', '40', '42', '44', '46', '48'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 50,
  },
  {
    ...base,
    id: 'seed-loafer-camurca-azul-nevoa',
    slug: 'loafer-camurca-azul-nevoa',
    name: 'Loafer de Camurça',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Loafer de camurça com pesponto aparente e solado creme leve. Vai de calça de alfaiataria a chino, sem meia à mostra.',
    fabric: 'Camurça',
    color_name: 'Azul Névoa',
    hex_color: '#7C8CA3',
    image_url: '/produtos/loafer-camurca-azul-nevoa.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 60,
  },
  {
    ...base,
    id: 'seed-tenis-couro-tricolor-caramelo',
    slug: 'tenis-couro-tricolor-caramelo',
    name: 'Tênis de Couro Tricolor',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Cabedal em couro branco com recortes em preto e caramelo e um toque de laranja no calcanhar. Solado alto e leve.',
    fabric: 'Couro',
    color_name: 'Branco, Preto e Caramelo',
    hex_color: '#EDEBE6',
    image_url: '/produtos/tenis-couro-tricolor-caramelo.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'esporte'],
    climates: [],
    formality: 1,
    is_featured: false,
    sort_order: 70,
  },
  {
    ...base,
    id: 'seed-tenis-listras-calcanhar-vermelho',
    slug: 'tenis-listras-calcanhar-vermelho',
    name: 'Tênis de Couro com Listras',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Couro branco com duas listras pretas e calcanhar vermelho. Solado robusto e limpo, para chino, alfaiataria leve ou jeans.',
    fabric: 'Couro',
    color_name: 'Branco e Preto',
    hex_color: '#F4F4F2',
    image_url: '/produtos/tenis-listras-calcanhar-vermelho.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'esporte'],
    climates: [],
    formality: 1,
    is_featured: false,
    sort_order: 80,
  },
  {
    ...base,
    id: 'seed-tenis-colorblock-preto-branco',
    slug: 'tenis-colorblock-preto-branco',
    name: 'Tênis Colorblock',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Recortes em preto, branco e cinza sobre solado branco alto. Um tênis com presença para looks monocromáticos.',
    fabric: 'Couro e camurça',
    color_name: 'Preto, Branco e Cinza',
    hex_color: '#2A2B2E',
    image_url: '/produtos/tenis-colorblock-preto-branco.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'esporte'],
    climates: [],
    formality: 1,
    is_featured: false,
    sort_order: 90,
  },
  {
    ...base,
    id: 'seed-tenis-couro-minimalista-branco',
    slug: 'tenis-couro-minimalista-branco',
    name: 'Tênis de Couro Minimalista',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Todo branco, em couro macio e sem logos. O tênis que resolve qualquer look casual refinado e acompanha até alfaiataria leve.',
    fabric: 'Couro',
    color_name: 'Branco',
    hex_color: '#F7F7F5',
    image_url: '/produtos/tenis-couro-minimalista-branco.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'esporte', 'jantar'],
    climates: [],
    formality: 2,
    is_featured: true,
    sort_order: 100,
  },
  {
    ...base,
    id: 'seed-tenis-listras-calcanhar-caramelo',
    slug: 'tenis-listras-calcanhar-caramelo',
    name: 'Tênis de Couro com Listras',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Couro branco com duas listras pretas e calcanhar caramelo. Combina com linho, chino claro e tons de terra.',
    fabric: 'Couro',
    color_name: 'Branco e Caramelo',
    hex_color: '#F1EFE9',
    image_url: '/produtos/tenis-listras-calcanhar-caramelo.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'esporte'],
    climates: [],
    formality: 1,
    is_featured: false,
    sort_order: 110,
  },
  {
    ...base,
    id: 'seed-derby-couro-solado-tratorado-conhaque',
    slug: 'derby-couro-solado-tratorado-conhaque',
    name: 'Derby de Couro com Solado Tratorado',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Couro conhaque polido com solado tratorado creme e cadarço encerado. Formal o bastante para o trabalho, moderno o bastante para o jantar.',
    fabric: 'Couro',
    color_name: 'Conhaque',
    hex_color: '#8A4B22',
    image_url: '/produtos/derby-couro-solado-tratorado-conhaque.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['trabalho', 'jantar', 'casual', 'festa'],
    climates: ['ameno', 'frio'],
    formality: 3,
    is_featured: true,
    sort_order: 120,
  },
  {
    ...base,
    id: 'seed-polo-trico-off-white',
    slug: 'polo-trico-off-white',
    name: 'Polo de Tricô',
    category: 'Malharia',
    slot: 'superior',
    description: 'Polo de tricô com três botões, punhos e barra canelados. Veste com calça de alfaiataria ou chino e dispensa a camisa social.',
    fabric: 'Tricô de algodão',
    color_name: 'Off-White',
    hex_color: '#EFEAE0',
    image_url: '/produtos/polo-trico-off-white.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte', 'trabalho'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: true,
    sort_order: 130,
  },
  {
    ...base,
    id: 'seed-polo-trico-azul-ceu',
    slug: 'polo-trico-azul-ceu',
    name: 'Polo de Tricô',
    category: 'Malharia',
    slot: 'superior',
    description: 'Polo de tricô com três botões, punhos e barra canelados. Veste com calça de alfaiataria ou chino e dispensa a camisa social.',
    fabric: 'Tricô de algodão',
    color_name: 'Azul Céu',
    hex_color: '#5F86BE',
    image_url: '/produtos/polo-trico-azul-ceu.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte', 'trabalho'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 140,
  },
  {
    ...base,
    id: 'seed-polo-trico-preto',
    slug: 'polo-trico-preto',
    name: 'Polo de Tricô',
    category: 'Malharia',
    slot: 'superior',
    description: 'Polo de tricô com três botões, punhos e barra canelados. Veste com calça de alfaiataria ou chino e dispensa a camisa social.',
    fabric: 'Tricô de algodão',
    color_name: 'Preto',
    hex_color: '#1C1D20',
    image_url: '/produtos/polo-trico-preto.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte', 'trabalho'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 150,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-caramelo',
    slug: 'camiseta-gola-alta-caramelo',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Caramelo',
    hex_color: '#A67B3E',
    image_url: '/produtos/camiseta-gola-alta-caramelo.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: ['morena', 'parda', 'negra'],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 160,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-branco',
    slug: 'camiseta-gola-alta-branco',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Branco',
    hex_color: '#F5F5F3',
    image_url: '/produtos/camiseta-gola-alta-branco.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 170,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-preto',
    slug: 'camiseta-gola-alta-preto',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Preto',
    hex_color: '#121316',
    image_url: '/produtos/camiseta-gola-alta-preto.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: true,
    sort_order: 180,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-verde-floresta',
    slug: 'camiseta-gola-alta-verde-floresta',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Verde Floresta',
    hex_color: '#1F4A38',
    image_url: '/produtos/camiseta-gola-alta-verde-floresta.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 190,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-azul-marinho',
    slug: 'camiseta-gola-alta-azul-marinho',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Azul Marinho',
    hex_color: '#17305E',
    image_url: '/produtos/camiseta-gola-alta-azul-marinho.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 200,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-creme',
    slug: 'camiseta-gola-alta-creme',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Creme',
    hex_color: '#F1E9D2',
    image_url: '/produtos/camiseta-gola-alta-creme.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 210,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-cinza-chumbo',
    slug: 'camiseta-gola-alta-cinza-chumbo',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Cinza Chumbo',
    hex_color: '#5B6166',
    image_url: '/produtos/camiseta-gola-alta-cinza-chumbo.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 220,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-marrom-cafe',
    slug: 'camiseta-gola-alta-marrom-cafe',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Marrom Café',
    hex_color: '#5A3B2B',
    image_url: '/produtos/camiseta-gola-alta-marrom-cafe.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: ['morena', 'parda', 'negra'],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 230,
  },
];

export const SEED_PRODUCTS: Product[] = RAW_SEED_PRODUCTS.map((p) => ({
  ...p,
  price_cents: getProductPriceCents(p.slug),
}));
