// Acervo inicial: as peças reais da Titi's Store (fotos em /public/produtos).
// Exibido quando o catálogo do Supabase está vazio ou indisponível; as mesmas peças
// estão em supabase/produtos.sql. Gerado a partir de uma lista única — edite lá e regenere.
import type { Product } from './types';

function getProductPriceCents(slug?: string | null): number {
  const s = slug || '';
  if (s.includes('alfaiataria-regulador')) return 28990;
  if (s.includes('alfaiataria-cordao')) return 26990;
  if (s.includes('chino')) return 24990;
  if (s.includes('derby')) return 42990;
  if (s.includes('loafer')) return 38990;
  if (s.includes('tenis-couro-minimalista')) return 32990;
  if (s.includes('tenis')) return 34990;
  if (s.includes('polo')) return 19990;
  if (s.includes('camiseta-gola-alta')) return 14990;
  return 24990;
}

const base = {
  season_compatibility: [] as string[],
  is_active: true,
  price_cents: 24990,
};

const RAW_SEED_PRODUCTS: Product[] = [
  {
    ...base,
    id: 'seed-calca-alfaiataria-regulador-cinza-grafite',
    slug: 'calca-alfaiataria-regulador-cinza-grafite',
    name: 'Calça de Alfaiataria com Regulador',
    category: 'Calças',
    slot: 'inferior',
    description: 'Regulador lateral em metal e cós limpo: veste sem cinto e afina a silhueta. Caimento slim com barra no ponto para tênis ou loafer.',
    fabric: 'Sarja com elastano',
    color_name: 'Cinza Grafite',
    hex_color: '#4A4D52',
    image_url: '/produtos/calca-alfaiataria-regulador-cinza-grafite.jpg',
    gallery: ['/produtos/calca-alfaiataria-regulador-cinza-grafite-2.jpg'],
    sizes: ['38', '40', '42', '44', '46', '48'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'esporte'],
    climates: [],
    formality: 3,
    is_featured: true,
    sort_order: 10,
  },
  {
    ...base,
    id: 'seed-calca-chino-slim-azul-marinho',
    slug: 'calca-chino-slim-azul-marinho',
    name: 'Calça Chino Slim',
    category: 'Calças',
    slot: 'inferior',
    description: 'Chino de sarja com elastano, bolsos faca e barra reta. A base mais versátil do guarda-roupa: do escritório ao jantar.',
    fabric: 'Sarja de algodão com elastano',
    color_name: 'Azul Marinho',
    hex_color: '#1F2D45',
    image_url: '/produtos/calca-chino-slim-azul-marinho.jpg',
    gallery: [],
    sizes: ['38', '40', '42', '44', '46', '48'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'esporte'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 20,
  },
  {
    ...base,
    id: 'seed-calca-chino-slim-off-white',
    slug: 'calca-chino-slim-off-white',
    name: 'Calça Chino Slim',
    category: 'Calças',
    slot: 'inferior',
    description: 'Chino claro de sarja com elastano, bolsos faca e barra reta. Ilumina o look e combina com camurça, caramelo e tons de terra.',
    fabric: 'Sarja de algodão com elastano',
    color_name: 'Off-White',
    hex_color: '#E9E1D2',
    image_url: '/produtos/calca-chino-slim-off-white.jpg',
    gallery: [],
    sizes: ['38', '40', '42', '44', '46', '48'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 30,
  },
  {
    ...base,
    id: 'seed-calca-alfaiataria-regulador-preto',
    slug: 'calca-alfaiataria-regulador-preto',
    name: 'Calça de Alfaiataria com Regulador',
    category: 'Calças',
    slot: 'inferior',
    description: 'Preto absoluto com regulador lateral em metal e cós limpo. Caimento slim, sem cinto, para noites e ocasiões que pedem sobriedade.',
    fabric: 'Sarja com elastano',
    color_name: 'Preto',
    hex_color: '#101114',
    image_url: '/produtos/calca-alfaiataria-regulador-preto.jpg',
    gallery: ['/produtos/calca-alfaiataria-regulador-preto-2.jpg'],
    sizes: ['38', '40', '42', '44', '46', '48'],
    skin_tones: [],
    occasions: ['trabalho', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 4,
    is_featured: false,
    sort_order: 40,
  },
  {
    ...base,
    id: 'seed-calca-alfaiataria-cordao-azul-marinho',
    slug: 'calca-alfaiataria-cordao-azul-marinho',
    name: 'Calça de Alfaiataria com Cordão',
    category: 'Calças',
    slot: 'inferior',
    description: 'Vinco frontal marcado e cós com cordão: aparência de alfaiataria com conforto de malha. Disponível também em preto, marrom e azul petróleo.',
    fabric: 'Malha de alfaiataria',
    color_name: 'Azul Marinho',
    hex_color: '#1B2A4A',
    image_url: '/produtos/calca-alfaiataria-cordao-azul-marinho.jpg',
    gallery: ['/produtos/calca-alfaiataria-cordao-azul-marinho-2.jpg'],
    sizes: ['38', '40', '42', '44', '46', '48'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 50,
  },
  {
    ...base,
    id: 'seed-loafer-camurca-azul-nevoa',
    slug: 'loafer-camurca-azul-nevoa',
    name: 'Loafer de Camurça',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Loafer de camurça com pesponto aparente e solado creme leve. Vai de calça de alfaiataria a chino, sem meia à mostra.',
    fabric: 'Camurça',
    color_name: 'Azul Névoa',
    hex_color: '#7C8CA3',
    image_url: '/produtos/loafer-camurca-azul-nevoa.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 60,
  },
  {
    ...base,
    id: 'seed-tenis-couro-tricolor-caramelo',
    slug: 'tenis-couro-tricolor-caramelo',
    name: 'Tênis de Couro Tricolor',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Cabedal em couro branco com recortes em preto e caramelo e um toque de laranja no calcanhar. Solado alto e leve.',
    fabric: 'Couro',
    color_name: 'Branco, Preto e Caramelo',
    hex_color: '#EDEBE6',
    image_url: '/produtos/tenis-couro-tricolor-caramelo.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'esporte'],
    climates: [],
    formality: 1,
    is_featured: false,
    sort_order: 70,
  },
  {
    ...base,
    id: 'seed-tenis-listras-calcanhar-vermelho',
    slug: 'tenis-listras-calcanhar-vermelho',
    name: 'Tênis de Couro com Listras',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Couro branco com duas listras pretas e calcanhar vermelho. Solado robusto e limpo, para chino, alfaiataria leve ou jeans.',
    fabric: 'Couro',
    color_name: 'Branco e Preto',
    hex_color: '#F4F4F2',
    image_url: '/produtos/tenis-listras-calcanhar-vermelho.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'esporte'],
    climates: [],
    formality: 1,
    is_featured: false,
    sort_order: 80,
  },
  {
    ...base,
    id: 'seed-tenis-colorblock-preto-branco',
    slug: 'tenis-colorblock-preto-branco',
    name: 'Tênis Colorblock',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Recortes em preto, branco e cinza sobre solado branco alto. Um tênis com presença para looks monocromáticos.',
    fabric: 'Couro e camurça',
    color_name: 'Preto, Branco e Cinza',
    hex_color: '#2A2B2E',
    image_url: '/produtos/tenis-colorblock-preto-branco.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'esporte'],
    climates: [],
    formality: 1,
    is_featured: false,
    sort_order: 90,
  },
  {
    ...base,
    id: 'seed-tenis-couro-minimalista-branco',
    slug: 'tenis-couro-minimalista-branco',
    name: 'Tênis de Couro Minimalista',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Todo branco, em couro macio e sem logos. O tênis que resolve qualquer look casual refinado e acompanha até alfaiataria leve.',
    fabric: 'Couro',
    color_name: 'Branco',
    hex_color: '#F7F7F5',
    image_url: '/produtos/tenis-couro-minimalista-branco.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'esporte', 'jantar'],
    climates: [],
    formality: 2,
    is_featured: true,
    sort_order: 100,
  },
  {
    ...base,
    id: 'seed-tenis-listras-calcanhar-caramelo',
    slug: 'tenis-listras-calcanhar-caramelo',
    name: 'Tênis de Couro com Listras',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Couro branco com duas listras pretas e calcanhar caramelo. Combina com linho, chino claro e tons de terra.',
    fabric: 'Couro',
    color_name: 'Branco e Caramelo',
    hex_color: '#F1EFE9',
    image_url: '/produtos/tenis-listras-calcanhar-caramelo.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'esporte'],
    climates: [],
    formality: 1,
    is_featured: false,
    sort_order: 110,
  },
  {
    ...base,
    id: 'seed-derby-couro-solado-tratorado-conhaque',
    slug: 'derby-couro-solado-tratorado-conhaque',
    name: 'Derby de Couro com Solado Tratorado',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Couro conhaque polido com solado tratorado creme e cadarço encerado. Formal o bastante para o trabalho, moderno o bastante para o jantar.',
    fabric: 'Couro',
    color_name: 'Conhaque',
    hex_color: '#8A4B22',
    image_url: '/produtos/derby-couro-solado-tratorado-conhaque.jpg',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    skin_tones: [],
    occasions: ['trabalho', 'jantar', 'casual', 'festa'],
    climates: ['ameno', 'frio'],
    formality: 3,
    is_featured: true,
    sort_order: 120,
  },
  {
    ...base,
    id: 'seed-polo-trico-off-white',
    slug: 'polo-trico-off-white',
    name: 'Polo de Tricô',
    category: 'Malharia',
    slot: 'superior',
    description: 'Polo de tricô com três botões, punhos e barra canelados. Veste com calça de alfaiataria ou chino e dispensa a camisa social.',
    fabric: 'Tricô de algodão',
    color_name: 'Off-White',
    hex_color: '#EFEAE0',
    image_url: '/produtos/polo-trico-off-white.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte', 'trabalho'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: true,
    sort_order: 130,
  },
  {
    ...base,
    id: 'seed-polo-trico-azul-ceu',
    slug: 'polo-trico-azul-ceu',
    name: 'Polo de Tricô',
    category: 'Malharia',
    slot: 'superior',
    description: 'Polo de tricô com três botões, punhos e barra canelados. Veste com calça de alfaiataria ou chino e dispensa a camisa social.',
    fabric: 'Tricô de algodão',
    color_name: 'Azul Céu',
    hex_color: '#5F86BE',
    image_url: '/produtos/polo-trico-azul-ceu.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte', 'trabalho'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 140,
  },
  {
    ...base,
    id: 'seed-polo-trico-preto',
    slug: 'polo-trico-preto',
    name: 'Polo de Tricô',
    category: 'Malharia',
    slot: 'superior',
    description: 'Polo de tricô com três botões, punhos e barra canelados. Veste com calça de alfaiataria ou chino e dispensa a camisa social.',
    fabric: 'Tricô de algodão',
    color_name: 'Preto',
    hex_color: '#1C1D20',
    image_url: '/produtos/polo-trico-preto.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte', 'trabalho'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 150,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-caramelo',
    slug: 'camiseta-gola-alta-caramelo',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Caramelo',
    hex_color: '#A67B3E',
    image_url: '/produtos/camiseta-gola-alta-caramelo.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: ['morena', 'parda', 'negra'],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 160,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-branco',
    slug: 'camiseta-gola-alta-branco',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Branco',
    hex_color: '#F5F5F3',
    image_url: '/produtos/camiseta-gola-alta-branco.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 170,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-preto',
    slug: 'camiseta-gola-alta-preto',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Preto',
    hex_color: '#121316',
    image_url: '/produtos/camiseta-gola-alta-preto.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: true,
    sort_order: 180,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-verde-floresta',
    slug: 'camiseta-gola-alta-verde-floresta',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Verde Floresta',
    hex_color: '#1F4A38',
    image_url: '/produtos/camiseta-gola-alta-verde-floresta.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 190,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-azul-marinho',
    slug: 'camiseta-gola-alta-azul-marinho',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Azul Marinho',
    hex_color: '#17305E',
    image_url: '/produtos/camiseta-gola-alta-azul-marinho.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 200,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-creme',
    slug: 'camiseta-gola-alta-creme',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Creme',
    hex_color: '#F1E9D2',
    image_url: '/produtos/camiseta-gola-alta-creme.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 210,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-cinza-chumbo',
    slug: 'camiseta-gola-alta-cinza-chumbo',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Cinza Chumbo',
    hex_color: '#5B6166',
    image_url: '/produtos/camiseta-gola-alta-cinza-chumbo.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 220,
  },
  {
    ...base,
    id: 'seed-camiseta-gola-alta-marrom-cafe',
    slug: 'camiseta-gola-alta-marrom-cafe',
    name: 'Camiseta Gola Alta',
    category: 'Malharia',
    slot: 'superior',
    description: 'Gola alta canelada e modelagem slim que valoriza ombros e braços. Malha encorpada, sem transparência, que segura o caimento o dia todo.',
    fabric: 'Malha de algodão com elastano',
    color_name: 'Marrom Café',
    hex_color: '#5A3B2B',
    image_url: '/produtos/camiseta-gola-alta-marrom-cafe.jpg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: ['morena', 'parda', 'negra'],
    occasions: ['casual', 'barzinho', 'jantar', 'esporte'],
    climates: ['quente', 'ameno'],
    formality: 2,
    is_featured: false,
    sort_order: 230,
  },
  {
    ...base,
    id: 'woo-gold-milan-white-3',
    slug: 'gold-milan-white-3',
    name: 'Gold Milan white',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Branco',
    hex_color: '#F7F7F5',
    image_url: '/produtos/IMG_8749-2.jpeg',
    gallery: ['/produtos/534f26b5-4e6d-42e1-9b78-666108d320b4-2.jpeg', '/produtos/25bf2866-4635-4512-b5b1-445f263b5b64-2.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: true,
    sort_order: 10,
    price_cents: 44999,
  },
  {
    ...base,
    id: 'woo-gold-milan-white-2',
    slug: 'gold-milan-white-2',
    name: 'Gold Milan white',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Branco',
    hex_color: '#F7F7F5',
    image_url: '/produtos/IMG_8749-1.jpeg',
    gallery: ['/produtos/534f26b5-4e6d-42e1-9b78-666108d320b4-1.jpeg', '/produtos/25bf2866-4635-4512-b5b1-445f263b5b64-1.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: true,
    sort_order: 20,
    price_cents: 44999,
  },
  {
    ...base,
    id: 'woo-gold-milan-white',
    slug: 'gold-milan-white',
    name: 'Gold Milan white',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Branco',
    hex_color: '#F7F7F5',
    image_url: '/produtos/IMG_8749.jpeg',
    gallery: ['/produtos/534f26b5-4e6d-42e1-9b78-666108d320b4.jpeg', '/produtos/25bf2866-4635-4512-b5b1-445f263b5b64.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: true,
    sort_order: 30,
    price_cents: 44999,
  },
  {
    ...base,
    id: 'woo-heritage-boot',
    slug: 'heritage-boot',
    name: 'Heritage boot',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Bota em couro legítimo nobre',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_7854.jpeg',
    gallery: ['/produtos/IMG_7856.jpeg', '/produtos/IMG_7853.jpeg', '/produtos/IMG_7852.jpeg', '/produtos/IMG_7855.jpeg', '/produtos/IMG_7850.jpeg', '/produtos/IMG_7851.jpeg', '/produtos/IMG_7849.jpeg', '/produtos/IMG_7848.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: true,
    sort_order: 40,
    price_cents: 49999,
  },
  {
    ...base,
    id: 'woo-chinelo-copacabana',
    slug: 'chinelo-copacabana',
    name: 'Chinelo copacabana',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Chinelo em couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_7862.png',
    gallery: [],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: true,
    sort_order: 50,
    price_cents: 19999,
  },
  {
    ...base,
    id: 'woo-oculos-low-camufle',
    slug: 'oculos-low-camufle',
    name: 'Oculos low camufle',
    category: 'Acessórios',
    slot: 'acessorio',
    description: 'Óculos armação',
    fabric: 'Metal e acetato',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_7833.png',
    gallery: ['/produtos/IMG_7826.jpeg', '/produtos/IMG_7817-scaled-e1778528809628.png'],
    sizes: ['Único'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: true,
    sort_order: 60,
    price_cents: 36999,
  },
  {
    ...base,
    id: 'woo-mosc-over',
    slug: 'mosc-over',
    name: 'Mosc over',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/29d4949f-d79d-40e6-ada8-b54cbb3feb61.jpeg',
    gallery: ['/produtos/0587c11a-d540-401d-864f-1574eca83053.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: true,
    sort_order: 70,
    price_cents: 43999,
  },
  {
    ...base,
    id: 'woo-loafer-mocca-italiano',
    slug: 'loafer-mocca-italiano',
    name: 'Loafer mocca italiano',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Calçado LOAFER mocassim italiano em couro legítimo e camurçado',
    fabric: 'Couro nobre',
    color_name: 'Mocca',
    hex_color: '#6B4423',
    image_url: '/produtos/IMG_4849.jpeg',
    gallery: ['/produtos/IMG_4850.jpeg', '/produtos/IMG_4851.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: true,
    sort_order: 80,
    price_cents: 48999,
  },
  {
    ...base,
    id: 'woo-blub-scol-fler',
    slug: 'blub-scol-fler',
    name: 'Blub scol fler',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Calçado em couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_6644.jpeg',
    gallery: ['/produtos/IMG_6643.jpeg', '/produtos/IMG_6645.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 90,
    price_cents: 45999,
  },
  {
    ...base,
    id: 'woo-black-scott',
    slug: 'black-scott',
    name: 'Black scott',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Calçado todo em couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Preto',
    hex_color: '#101114',
    image_url: '/produtos/IMG_6636.jpeg',
    gallery: ['/produtos/IMG_6634.jpeg', '/produtos/IMG_6637.jpeg', '/produtos/IMG_6638.jpeg', '/produtos/IMG_6639.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 100,
    price_cents: 49999,
  },
  {
    ...base,
    id: 'woo-blow-snap',
    slug: 'blow-snap',
    name: 'Blow snap',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Calçado em couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_6648.jpeg',
    gallery: ['/produtos/IMG_6649.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 110,
    price_cents: 42999,
  },
  {
    ...base,
    id: 'woo-alban-black',
    slug: 'alban-black',
    name: 'Alban black',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Conforto que Você Sente, Estilo que Você Vê. Conheça o ALBAN. Imagine um calçado que não apenas complementa seu look, mas o transforma. O ALBAN foi projetado para quem não abre mão do design arrojado e do conforto duradouro. O solado geométrico absorve o impacto, enquanto o couro macio abraça seu pé. ✨ Do escritório ao happy hour, esteja sempre à frente. O ALBAN Black é o seu novo item essencial. 👉 Não espere esgotar. Invista em você mesmo e eleve sua coleção. Compre hoje e receba no conforto de casa.',
    fabric: 'Couro nobre',
    color_name: 'Preto',
    hex_color: '#101114',
    image_url: '/produtos/IMG_5529.png',
    gallery: ['/produtos/IMG_5514.jpeg', '/produtos/IMG_5513.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 120,
    price_cents: 48999,
  },
  {
    ...base,
    id: 'woo-nimbus-black',
    slug: 'nimbus-black',
    name: 'Nimbus Black',
    category: 'Calçados',
    slot: 'calcado',
    description: '&#8220;Nimbus Black&#8221; (Nimbus evoca nuvem, leveza e a ideia de flutuar sobre a plataforma) • Legenda: &#8220;Estilo que te eleva. Com uma plataforma confortável e um visual monocromático sofisticado, o Nimbus Black é o companheiro perfeito para quem busca conforto sem abrir mão da tendência.&#8221;',
    fabric: 'Couro nobre',
    color_name: 'Preto',
    hex_color: '#101114',
    image_url: '/produtos/IMG_5515.jpeg',
    gallery: ['/produtos/IMG_5516.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 130,
    price_cents: 45999,
  },
  {
    ...base,
    id: 'woo-bermuda-em-linho',
    slug: 'bermuda-em-linho',
    name: 'Bermuda em linho',
    category: 'Calças',
    slot: 'inferior',
    description: 'Bermudas em linho',
    fabric: 'Algodão e elastano',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4894.jpeg',
    gallery: ['/produtos/IMG_4895.jpeg', '/produtos/IMG_4896.jpeg', '/produtos/IMG_4893.jpeg'],
    sizes: ['38', '40', '42', '44', '46'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 140,
    price_cents: 23999,
  },
  {
    ...base,
    id: 'woo-blazer-alpha',
    slug: 'blazer-alpha',
    name: 'Blazer Alpha',
    category: 'Alfaiataria',
    slot: 'sobreposicao',
    description: 'Blazer alfaitaria',
    fabric: 'Lã fria e elastano',
    color_name: 'Bege Areia',
    hex_color: '#D2B58C',
    image_url: '/produtos/4a978983-bb1a-4773-9ff2-a27ec7104859.jpeg',
    gallery: ['/produtos/ff36ef76-aacd-44fb-bacf-7894559778ff.jpeg', '/produtos/06421e63-91f1-4ca6-aa7e-3edf7274e59c.jpeg', '/produtos/e64dad73-5e4b-43d3-91e0-ba007fefe906.jpeg', '/produtos/0931c042-3fa9-4672-8043-16bbabaf5130.jpeg', '/produtos/dd0fcaac-e2a3-4dfd-9fe7-6a25cdcbecdf.jpeg', '/produtos/cb8db3bc-adef-415e-a3d0-42155d4d38b4.jpeg', '/produtos/eabd5432-85c8-4928-a0d7-59648bd620e6.jpeg', '/produtos/05c5a834-5059-4eec-9e9b-181afe52ae1c.jpeg'],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 4,
    is_featured: false,
    sort_order: 150,
    price_cents: 65999,
  },
  {
    ...base,
    id: 'woo-bone-dutih',
    slug: 'bone-dutih',
    name: 'Boné Dútih',
    category: 'Acessórios',
    slot: 'acessorio',
    description: 'Boné em tecido flow',
    fabric: 'Metal e acetato',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/7c7be826-cc84-4909-8d35-3f2c9bc324be.jpeg',
    gallery: [],
    sizes: ['Único'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 160,
    price_cents: 8999,
  },
  {
    ...base,
    id: 'woo-gold-white-couro',
    slug: 'gold-white-couro',
    name: 'Gold white couro',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Calçado em couro modelo bem versátil',
    fabric: 'Couro nobre',
    color_name: 'Branco',
    hex_color: '#F7F7F5',
    image_url: '/produtos/IMG_4845.jpeg',
    gallery: ['/produtos/IMG_4846.jpeg', '/produtos/IMG_4847.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 170,
    price_cents: 46999,
  },
  {
    ...base,
    id: 'woo-chinelo-hawai-em-couro',
    slug: 'chinelo-hawai-em-couro',
    name: 'Chinelo Hawai em couro',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Chinelo em couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4857.jpeg',
    gallery: ['/produtos/IMG_4858.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 180,
    price_cents: 18999,
  },
  {
    ...base,
    id: 'woo-lady-word',
    slug: 'lady-word',
    name: 'Lady word',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Calado em couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4860.jpeg',
    gallery: ['/produtos/IMG_4859.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 190,
    price_cents: 44999,
  },
  {
    ...base,
    id: 'woo-alfaiataria-tech',
    slug: 'alfaiataria-tech',
    name: 'Alfaiataria tech',
    category: 'Calças',
    slot: 'inferior',
    description: 'Calça alfaiataria tech com ajustes',
    fabric: 'Lã fria e elastano',
    color_name: 'Preto',
    hex_color: '#101114',
    image_url: '/produtos/IMG_3133.jpeg',
    gallery: ['/produtos/IMG_3134.jpeg', '/produtos/IMG_3137.jpeg', '/produtos/IMG_3135.jpeg'],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 4,
    is_featured: false,
    sort_order: 200,
    price_cents: 35999,
  },
  {
    ...base,
    id: 'woo-camisa-gola-media',
    slug: 'camisa-gola-media',
    name: 'Camisa gola média',
    category: 'Camisaria',
    slot: 'superior',
    description: 'Camisa gola média',
    fabric: 'Algodão e elastano',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4688.jpeg',
    gallery: ['/produtos/IMG_4689.jpeg', '/produtos/IMG_4687.jpeg'],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 210,
    price_cents: 16999,
  },
  {
    ...base,
    id: 'woo-oculos-flow',
    slug: 'oculos-flow',
    name: 'Óculos FLOW',
    category: 'Acessórios',
    slot: 'acessorio',
    description: 'Armação óculos para grau',
    fabric: 'Metal e acetato',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4692.jpeg',
    gallery: ['/produtos/IMG_4690.jpeg'],
    sizes: ['Único'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 220,
    price_cents: 28999,
  },
  {
    ...base,
    id: 'woo-chinelo-slide',
    slug: 'chinelo-slide',
    name: 'Chinelo slide',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Chinelo slide , o estilo e o conforto que você merece em todos ambientes casuais descontraídos',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4509-1.png',
    gallery: ['/produtos/IMG_4507-1.jpeg', '/produtos/IMG_4506-1.jpeg', '/produtos/IMG_4508.png'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 230,
    price_cents: 28999,
  },
  {
    ...base,
    id: 'woo-camisa-em-linho',
    slug: 'camisa-em-linho',
    name: 'Camisa em linho',
    category: 'Camisaria',
    slot: 'superior',
    description: 'Camisas em linho gola padre',
    fabric: 'Algodão e elastano',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4684.jpeg',
    gallery: ['/produtos/IMG_4685.jpeg', '/produtos/IMG_4686.jpeg'],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 240,
    price_cents: 22999,
  },
  {
    ...base,
    id: 'woo-mochila-hummer',
    slug: 'mochila-hummer',
    name: 'Mochila hummer',
    category: 'Acessórios',
    slot: 'acessorio',
    description: 'Mochilas em couro legítimo nobre',
    fabric: 'Metal e acetato',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4680.jpeg',
    gallery: ['/produtos/IMG_4679.jpeg', '/produtos/IMG_4681.jpeg', '/produtos/IMG_4683.jpeg'],
    sizes: ['Único'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 250,
    price_cents: 69999,
  },
  {
    ...base,
    id: 'woo-mala-over-em-couro-legitimo',
    slug: 'mala-over-em-couro-legitimo',
    name: 'Mala over em couro legítimo',
    category: 'Acessórios',
    slot: 'acessorio',
    description: 'Mala over toda em Couro legítimo nobre',
    fabric: 'Metal e acetato',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4491.jpeg',
    gallery: [],
    sizes: ['Único'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 260,
    price_cents: 83999,
  },
  {
    ...base,
    id: 'woo-cinto-em-couro-legitimo',
    slug: 'cinto-em-couro-legitimo',
    name: 'Cinto em couro legítimo',
    category: 'Acessórios',
    slot: 'acessorio',
    description: 'Cinto em couro legítimo',
    fabric: 'Metal e acetato',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4635.jpeg',
    gallery: [],
    sizes: ['Único'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 270,
    price_cents: 12999,
  },
  {
    ...base,
    id: 'woo-birken',
    slug: 'birken',
    name: 'Birken',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Sandália unissex',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4668.jpeg',
    gallery: ['/produtos/IMG_4670.jpeg', '/produtos/IMG_4666.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 280,
    price_cents: 14999,
  },
  {
    ...base,
    id: 'woo-bag',
    slug: 'bag',
    name: 'Bag',
    category: 'Acessórios',
    slot: 'acessorio',
    description: 'Bag em couro legítimo nobre',
    fabric: 'Metal e acetato',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4516.jpeg',
    gallery: ['/produtos/IMG_4515.jpeg', '/produtos/IMG_4517.jpeg'],
    sizes: ['Único'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 290,
    price_cents: 33999,
  },
  {
    ...base,
    id: 'woo-t-shirt-egipcia',
    slug: 't-shirt-egipcia',
    name: 'T-shirt egípcia',
    category: 'Camisaria',
    slot: 'superior',
    description: 'Camiseta em algodão egípcios com elastano',
    fabric: 'Algodão e elastano',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4421.jpeg',
    gallery: ['/produtos/IMG_4420.jpeg', '/produtos/copy_ED6D813E-3E32-4774-A0AE-F86C68A309D1.png'],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 300,
    price_cents: 18999,
  },
  {
    ...base,
    id: 'woo-moscow-bold',
    slug: 'moscow-bold',
    name: 'Moscow bold',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Calado em couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4433.png',
    gallery: ['/produtos/IMG_4432.png', '/produtos/IMG_4434.png'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 310,
    price_cents: 48999,
  },
  {
    ...base,
    id: 'woo-over-snow',
    slug: 'over-snow',
    name: 'Over Snow',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Calçado em couro legítimo',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4480.png',
    gallery: ['/produtos/IMG_4481.png', '/produtos/25301228-4dd3-4109-8540-29213949e814.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 320,
    price_cents: 48999,
  },
  {
    ...base,
    id: 'woo-slide-dboa',
    slug: 'slide-dboa',
    name: 'Slide dböa',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Chinelo slide unissex',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4509.png',
    gallery: ['/produtos/IMG_4507.jpeg', '/produtos/IMG_4506.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 330,
    price_cents: 28999,
  },
  {
    ...base,
    id: 'woo-gold-mily-2',
    slug: 'gold-mily-2',
    name: 'Gold mily',
    category: 'Calçados',
    slot: 'calcado',
    description: 'O Gold Mily é a definição de luxo silencioso para os seus pés. Confeccionado inteiramente em couro legítimo selecionado, este calçado foi desenhado para quem não abre mão da sofisticação, mas exige o máximo de conforto para o dia a dia. Seu design clean e o solado robusto criam uma estética contemporânea que eleva qualquer visual básico a um novo patamar de estilo.',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4413-1.jpeg',
    gallery: ['/produtos/IMG_4414-1.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 340,
    price_cents: 43999,
  },
  {
    ...base,
    id: 'woo-gold-mily',
    slug: 'gold-mily',
    name: 'Gold mily',
    category: 'Calçados',
    slot: 'calcado',
    description: 'O Gold Mily é a definição de luxo silencioso para os seus pés. Confeccionado inteiramente em couro legítimo selecionado, este calçado foi desenhado para quem não abre mão da sofisticação, mas exige o máximo de conforto para o dia a dia. Seu design clean e o solado robusto criam uma estética contemporânea que eleva qualquer visual básico a um novo patamar de estilo.',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4413.jpeg',
    gallery: ['/produtos/IMG_4414.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 350,
    price_cents: 41999,
  },
  {
    ...base,
    id: 'woo-overscoot',
    slug: 'overscoot',
    name: 'Overscoot',
    category: 'Calçados',
    slot: 'calcado',
    description: 'O Overscoot chega para redefinir o conceito de calçado casual premium. Com um solado robusto e moderno, ele traz o peso visual da tendência streetwear sem perder a elegância. O detalhe em contraste no calcanhar e as faixas laterais minimalistas garantem personalidade a cada passo. • Design Contemporâneo: Solado elevado (flatform) que oferece altura e estilo com estabilidade. • Contraste Premium: Acabamento em branco clássico com detalhes em preto e um toque de cor no calcanhar. • O Look: A peça chave para quebrar a formalidade da calça de alfaiataria ou elevar o básico jeans com camiseta.',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4411.jpeg',
    gallery: ['/produtos/IMG_4412.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 360,
    price_cents: 48999,
  },
  {
    ...base,
    id: 'woo-t-shirt-100-algodao',
    slug: 't-shirt-100-algodao',
    name: 'T-shirt 100% algodão',
    category: 'Camisaria',
    slot: 'superior',
    description: 'A base de qualquer guarda-roupa inteligente começa aqui. Nossa camiseta básica é confeccionada com algodão 100% premium, garantindo uma peça extremamente macia, respirável e com caimento perfeito. É o equilíbrio ideal entre simplicidade e sofisticação. • Fibras Naturais: Permite que a pele respire, ideal para o clima tropical. • Acabamento Reforçado: Gola em ribana que não esgarça e costuras duplas para maior durabilidade. • Minimalismo: Sem logos aparentes, perfeita para composições casuais ou por baixo de blazers.',
    fabric: 'Algodão e elastano',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4404.jpeg',
    gallery: ['/produtos/IMG_4407.jpeg', '/produtos/IMG_4405.jpeg', '/produtos/IMG_4406.jpeg', '/produtos/IMG_4408.jpeg', '/produtos/IMG_4409.jpeg', '/produtos/IMG_4410.jpeg'],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 370,
    price_cents: 13999,
  },
  {
    ...base,
    id: 'woo-calca-alfaitaria',
    slug: 'calca-alfaitaria',
    name: 'Calça alfaitaria',
    category: 'Calças',
    slot: 'inferior',
    description: 'Eleve seu estilo com a nossa Calça Alfaiataria de corte reto e caimento impecável. Desenvolvida para transitar com facilidade entre o escritório e o jantar especial, esta peça combina a sofisticação clássica com o conforto que o dia a dia exige. • Destaques: Cintura alta com acabamento clean, bolsos laterais discretos e vincos frontais que alongam a silhueta. • Tecido: Crepe de alta gramatura (não amassa com facilidade). • Como usar: Combine com um blazer estruturado para um look power suit ou uma t-shirt de algodão para um visual high-low moderno',
    fabric: 'Algodão e elastano',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/IMG_4401.jpeg',
    gallery: ['/produtos/IMG_4396.jpeg', '/produtos/IMG_4398.jpeg', '/produtos/IMG_4399.jpeg', '/produtos/IMG_4397.jpeg', '/produtos/IMG_4403.jpeg', '/produtos/IMG_4402.jpeg'],
    sizes: ['38', '40', '42', '44', '46'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 2,
    is_featured: false,
    sort_order: 380,
    price_cents: 26999,
  },
  {
    ...base,
    id: 'woo-prisma-walk',
    slug: 'prisma-walk',
    name: 'Prisma walk',
    category: 'Calçados',
    slot: 'calcado',
    description: 'O Prisma Walk é a síntese da inovação visual com o artesanato clássico. Projetado para quem não abre mão de um design disruptivo, este calçado se destaca pelo seu solado geométrico tridimensional, que confere uma presença marcante e moderna a qualquer look. Fabricado com couro legítimo nobre, o modelo oferece uma experiência de uso superior, combinando a durabilidade e a respirabilidade do material natural com uma estética bold e urbana.',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/0086973f-38bb-45f1-b07a-3101a513ef9c.jpeg',
    gallery: ['/produtos/2aa5dc4d-db0e-450e-96f7-eb62eee951f2.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 390,
    price_cents: 48999,
  },
  {
    ...base,
    id: 'woo-old-bulb',
    slug: 'old-bulb',
    name: 'Old bulb',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Eleve seu estilo urbano com o Prisma Walk old bulb. Este modelo une a sofisticação do couro legítimo a um solado disruptivo, criando um calçado que é, ao mesmo tempo, uma peça de design e um aliado para o conforto diário. Seu grande diferencial está no solado tridimensional, com texturas que remetem a prismas, garantindo uma estética bold e moderna que não passa despercebida.',
    fabric: 'Couro nobre',
    color_name: 'Chumbo',
    hex_color: '#4A4D52',
    image_url: '/produtos/51a7f22c-c9af-4e86-8122-0c6e08a705dd.jpeg',
    gallery: ['/produtos/f670e2fe-d531-4c2b-91e3-5a4228a87693.jpeg'],
    sizes: ['38', '39', '40', '41', '42', '43'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 3,
    is_featured: false,
    sort_order: 400,
    price_cents: 46999,
  },
  {
    ...base,
    id: 'woo-bold-carbon',
    slug: 'bold-carbon',
    name: 'Bold Carbon',
    category: 'Calçados',
    slot: 'calcado',
    description: 'Sneaker minimalista em couro nobuck preto carbono com solado ergonômico.',
    fabric: 'Couro nobuck legítimo',
    color_name: 'Preto / Carbono',
    hex_color: '#211F22',
    image_url: '/produtos/IMG_3660.jpeg',
    gallery: [],
    sizes: ['P', 'M', 'G', 'GG'],
    skin_tones: [],
    occasions: ['trabalho', 'casual', 'barzinho', 'jantar', 'festa'],
    climates: [],
    formality: 4,
    is_featured: false,
    sort_order: 410,
    price_cents: 48999,
  },
];

export const SEED_PRODUCTS: Product[] = RAW_SEED_PRODUCTS.map((p) => ({
  ...p,
  price_cents: p.price_cents ?? getProductPriceCents(p.slug),
}));
